//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlykhoWPF.Model
{
    using QuanlykhoWPF.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Output : BaseViewModel
    {
        private string _id;
        public string Id { get => _id; set { _id = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _DateOutput;
        public Nullable<System.DateTime> DateOutput { get => _DateOutput; set { _DateOutput = value; OnPropertyChanged(); } }
        public virtual OutputInfo OutputInfo { get; set; }
    }
}
