//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlykhoWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id { get; set; }
        public int IdSuplier { get; set; }
        public string IdObject { get; set; }
        public Nullable<int> Quantitysp { get; set; }
        public Nullable<int> Quantityob { get; set; }
    
        public virtual Object Object { get; set; }
        public virtual Suplier Suplier { get; set; }
    }
}
